import { ctaSectionSchema } from "./schemas/cta-section.schema";
import { heroSectionSchema } from "./schemas/hero-section.schema";
import { textSectionSchema } from "./schemas/text-section.schema";
import { gridSectionSchema } from "./schemas/grid-section.schema";
import { trustLogosSchema } from "./schemas/trust-logos.schema";
import { CtaSectionBlock, HeroSectionBlock, TextSectionBlock, GridSectionBlock, TrustLogosBlock } from "./components";
import type { CmsFieldDefinition, EditableComponentDefinition } from "./types";

const appearanceFields: CmsFieldDefinition[] = [
  {
    name: "layoutPreset",
    label: "Aparencia da secao",
    type: "select",
    description: "Controla o ritmo visual sem liberar layout livre.",
    options: [
      { label: "Padrao", value: "default" },
      { label: "Compacto", value: "compact" },
      { label: "Dividido", value: "split" },
      { label: "Destaque", value: "feature" },
      { label: "Denso", value: "dense" },
    ],
  },
  {
    name: "backgroundPreset",
    label: "Fundo",
    type: "select",
    options: [
      { label: "Nenhum", value: "none" },
      { label: "Escuro solido", value: "solid-dark" },
      { label: "Claro solido", value: "solid-light" },
      { label: "Gradiente industrial", value: "industrial-gradient" },
      { label: "Imagem com overlay escuro", value: "image-dark-overlay" },
      { label: "Imagem com overlay vermelho", value: "image-red-overlay" },
      { label: "Split escuro + imagem", value: "split-dark-image" },
      { label: "Textura escura", value: "texture-dark" },
      { label: "Grid tecnico", value: "technical-grid" },
    ],
  },
  { name: "backgroundImageUrl", label: "Imagem de fundo", type: "media" },
  {
    name: "backgroundPosition",
    label: "Enquadramento do fundo",
    type: "select",
    options: [
      { label: "Centro", value: "center" },
      { label: "Topo", value: "top" },
      { label: "Base", value: "bottom" },
      { label: "Esquerda", value: "left" },
      { label: "Direita", value: "right" },
    ],
  },
  {
    name: "overlayStrength",
    label: "Intensidade do overlay",
    type: "select",
    description: "Use 60 ou 80 quando houver texto sobre imagem.",
    options: [
      { label: "20%", value: "20" },
      { label: "40%", value: "40" },
      { label: "60% recomendado", value: "60" },
      { label: "80% alto contraste", value: "80" },
    ],
  },
  {
    name: "overlayTone",
    label: "Tom do overlay",
    type: "select",
    options: [
      { label: "Preto", value: "black" },
      { label: "Vermelho RECOM", value: "red" },
      { label: "Aco", value: "steel" },
      { label: "Neutro", value: "neutral" },
    ],
  },
  { name: "textureEnabled", label: "Textura tecnica discreta", type: "checkbox" },
];

const gridAppearanceFields: CmsFieldDefinition[] = [
  {
    name: "gridPreset",
    label: "Layout dos cards",
    type: "select",
    options: [
      { label: "Automatico", value: "auto" },
      { label: "2 colunas", value: "two-columns" },
      { label: "3 colunas", value: "three-columns" },
      { label: "4 colunas", value: "four-columns" },
      { label: "Destaque a esquerda", value: "featured-left" },
      { label: "Primeiro destacado", value: "featured-first" },
      { label: "Denso", value: "dense" },
      { label: "Editorial", value: "editorial" },
    ],
  },
  {
    name: "gridGap",
    label: "Espacamento",
    type: "select",
    options: [
      { label: "Compacto", value: "compact" },
      { label: "Normal", value: "normal" },
      { label: "Relaxado", value: "relaxed" },
    ],
  },
  {
    name: "alignItems",
    label: "Alinhamento",
    type: "select",
    options: [
      { label: "Esticar cards", value: "stretch" },
      { label: "Alinhar pelo topo", value: "start" },
    ],
  },
  {
    name: "mobileBehavior",
    label: "Comportamento mobile",
    type: "select",
    options: [
      { label: "Empilhar", value: "stack" },
      { label: "Carrossel horizontal", value: "carousel" },
      { label: "Compacto", value: "compact" },
    ],
  },
  {
    name: "mediaMode",
    label: "Modo da imagem",
    type: "select",
    options: [
      { label: "Sem imagem", value: "none" },
      { label: "Logo", value: "logo" },
      { label: "Thumbnail", value: "thumbnail" },
      { label: "Capa", value: "cover" },
      { label: "Fundo", value: "background" },
      { label: "Split", value: "split" },
    ],
  },
  {
    name: "cardVariant",
    label: "Visual do card",
    type: "select",
    options: [
      { label: "Padrao", value: "default" },
      { label: "Industrial", value: "industrial" },
      { label: "Tecnico", value: "technical" },
      { label: "Catalogo", value: "catalog" },
      { label: "Promocao", value: "promotion" },
    ],
  },
  {
    name: "cardDensity",
    label: "Densidade",
    type: "select",
    options: [
      { label: "Compacta", value: "compact" },
      { label: "Normal", value: "normal" },
      { label: "Relaxada", value: "relaxed" },
    ],
  },
  {
    name: "imagePosition",
    label: "Enquadramento da imagem",
    type: "select",
    options: [
      { label: "Centro", value: "center" },
      { label: "Topo", value: "top" },
      { label: "Base", value: "bottom" },
      { label: "Esquerda", value: "left" },
      { label: "Direita", value: "right" },
    ],
  },
];

export const componentRegistry = {
  HeroSection: {
    type: "HeroSection",
    label: "Hero principal",
    description: "Banner de destaque com título, CTA e imagem ou carrossel.",
    category: "content",
    component: HeroSectionBlock,
    schema: heroSectionSchema,
    defaults: {
      eyebrow: "",
      title: "",
      subtitle: "",
      primaryCtaLabel: "Falar com a RECOM",
      primaryCtaHref: "/sobre#contato",
      secondaryCtaLabel: "",
      secondaryCtaHref: "",
      imageUrl: "",
      showCarousel: true,
      variant: "default",
      carouselSpeed: 5000,
      layoutPreset: "default",
      backgroundPreset: "industrial-gradient",
      backgroundPosition: "center",
      overlayStrength: 60,
      overlayTone: "black",
    },
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", description: "Texto curto acima do título." },
      { name: "title", label: "Título H1", type: "text", required: true },
      { name: "subtitle", label: "Subtítulo", type: "textarea", rows: 3 },
      { name: "primaryCtaLabel", label: "Botão Principal", type: "text" },
      { name: "primaryCtaHref", label: "Link Botão Principal", type: "text" },
      { name: "secondaryCtaLabel", label: "Botão Secundário", type: "text" },
      { name: "secondaryCtaHref", label: "Link Botão Secundário", type: "text" },
      { name: "imageUrl", label: "Imagem de Fundo", type: "media", description: "Imagem estática caso o carrossel esteja desativado." },
      { name: "showCarousel", label: "Ativar Carrossel", type: "checkbox" },
      { name: "carouselSpeed", label: "Velocidade (ms)", type: "number", description: "Tempo entre slides (ex: 5000)." },
      {
        name: "variant",
        label: "Estilo Visual",
        type: "select",
        options: [
          { label: "Padrão (Lado a Lado)", value: "default" },
          { label: "Split (Dividido)", value: "split" },
          { label: "Compacto (Centralizado)", value: "compact" },
          { label: "Full Width (Tela Cheia)", value: "full" },
          { label: "Simples (Apenas Texto)", value: "simple" },
          { label: "Industrial B2B", value: "industrial" },
          { label: "ConteÃºdo tÃ©cnico", value: "technical" },
          { label: "Contato / orÃ§amento", value: "contact" },
          { label: "CatÃ¡logo / hub", value: "catalog" },
        ],
      },
      ...appearanceFields,
    ],
    allowedVariants: ["default", "split", "compact", "full", "simple", "industrial", "technical", "contact", "catalog"],
    previewConfig: { layout: "full" },
    permissions: ["admin", "editor"],
    revisionStrategy: "snapshot",
  },
  TextSection: {
    type: "TextSection",
    label: "Texto Institucional",
    description: "Bloco para conteúdos textuais longos ou explicativos.",
    category: "content",
    component: TextSectionBlock,
    schema: textSectionSchema,
    defaults: {
      title: "",
      body: "",
      variant: "default",
      layoutPreset: "default",
      backgroundPreset: "none",
    },
    fields: [
      { name: "title", label: "Título da Seção", type: "text" },
      { name: "body", label: "Conteúdo (Markdown)", type: "textarea", required: true, rows: 10 },
      {
        name: "variant",
        label: "Estilo",
        type: "select",
        options: [
          { label: "Padrão", value: "default" },
          { label: "Destaque (Fundo Cinza)", value: "panel" },
          { label: "Editorial institucional", value: "editorial" },
          { label: "TÃ©cnico / fonte", value: "technical" },
          { label: "Compacto", value: "compact" },
          { label: "Nota / aviso", value: "note" },
        ],
      },
      ...appearanceFields,
    ],
    allowedVariants: ["default", "panel", "editorial", "technical", "compact", "note"],
    previewConfig: { layout: "contained" },
    permissions: ["admin", "editor"],
    revisionStrategy: "snapshot",
  },
  CtaSection: {
    type: "CtaSection",
    label: "Chamada para Ação (CTA)",
    description: "Seção de conversão com fundo contrastante e botões.",
    category: "cta",
    component: CtaSectionBlock,
    schema: ctaSectionSchema,
    defaults: {
      eyebrow: "",
      title: "",
      description: "",
      primaryCtaLabel: "Falar com a RECOM",
      primaryCtaHref: "/sobre#contato",
      secondaryCtaLabel: "",
      secondaryCtaHref: "",
      variant: "default",
      layoutPreset: "default",
      backgroundPreset: "industrial-gradient",
      backgroundPosition: "center",
      overlayStrength: 60,
      overlayTone: "black",
    },
    fields: [
      { name: "eyebrow", label: "Texto de Apoio", type: "text" },
      { name: "title", label: "Título de Impacto", type: "text", required: true },
      { name: "description", label: "Breve Descrição", type: "textarea", required: true, rows: 3 },
      { name: "primaryCtaLabel", label: "Texto Botão 1", type: "text", required: true },
      { name: "primaryCtaHref", label: "Link Botão 1", type: "text", required: true },
      { name: "secondaryCtaLabel", label: "Texto Botão 2", type: "text" },
      { name: "secondaryCtaHref", label: "Link Botão 2", type: "text" },
      {
        name: "variant",
        label: "Tema",
        type: "select",
        options: [
          { label: "Escuro (Padrão RECOM)", value: "default" },
          { label: "Claro", value: "light" },
          { label: "Azul Primário", value: "primary" },
          { label: "Preto Absoluto", value: "dark" },
          { label: "Contato / OrÃ§amento", value: "contact" },
          { label: "CatÃ¡logo oficial", value: "catalog" },
          { label: "Discreto", value: "quiet" },
        ],
      },
      ...appearanceFields,
    ],
    allowedVariants: ["default", "light", "primary", "dark", "contact", "catalog", "quiet"],
    previewConfig: { layout: "full" },
    permissions: ["admin", "editor"],
    revisionStrategy: "snapshot",
  },
  GridSection: {
    type: "GridSection",
    label: "Grade de Recursos",
    description: "Exibe diferenciais, serviços ou links em colunas.",
    category: "content",
    component: GridSectionBlock,
    schema: gridSectionSchema,
    defaults: {
      title: "",
      items: [],
      columns: "3",
      variant: "default",
      layoutPreset: "default",
      backgroundPreset: "none",
      gridPreset: "three-columns",
      gridGap: "normal",
      alignItems: "stretch",
      mobileBehavior: "stack",
      mediaMode: "none",
      cardVariant: "default",
      cardDensity: "normal",
      imagePosition: "center",
    },
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text" },
      { name: "title", label: "Título Principal", type: "text" },
      { name: "description", label: "Texto Introdutório", type: "textarea" },
      {
        name: "columns",
        label: "Número de Colunas",
        type: "select",
        options: [
          { label: "2 Colunas", value: "2" },
          { label: "3 Colunas", value: "3" },
          { label: "4 Colunas", value: "4" },
          { label: "5 Colunas", value: "5" },
          { label: "6 Colunas", value: "6" },
        ],
      },
      {
        name: "variant",
        label: "Estilo do Cartão",
        type: "select",
        options: [
          { label: "Padrão (Bordas)", value: "default" },
          { label: "Cartão Branco", value: "white" },
          { label: "Sutil (Fundo Cinza)", value: "gray" },
          { label: "Destaque (Azul)", value: "primary" },
          { label: "Fornecedor", value: "supplier" },
          { label: "Processo", value: "process" },
          { label: "TÃ©cnico", value: "technical" },
          { label: "PromoÃ§Ã£o", value: "promotion" },
        ],
      },
      {
        name: "items",
        label: "Adicionar Itens",
        type: "list",
        itemFields: [
          { name: "title", label: "Título do Item", type: "text", required: true },
          { name: "description", label: "Descrição", type: "textarea" },
          {
            name: "icon",
            label: "Ícone",
            type: "select",
            options: [
              { label: "Segurança (Escudo)", value: "shield" },
              { label: "Sucesso (Check)", value: "check" },
              { label: "Indústria (Fábrica)", value: "factory" },
              { label: "Suporte (Chave)", value: "wrench" },
              { label: "Localização (Pin)", value: "pin" },
              { label: "Produto (Caixa)", value: "package" },
            ],
          },
          { name: "linkLabel", label: "Texto do Link", type: "text" },
          { name: "linkHref", label: "URL do Link", type: "text" },
          { name: "imageUrl", label: "Imagem do item", type: "media" },
          { name: "imageAlt", label: "Texto alternativo", type: "text" },
          {
            name: "imagePosition",
            label: "Enquadramento",
            type: "select",
            options: [
              { label: "Centro", value: "center" },
              { label: "Topo", value: "top" },
              { label: "Base", value: "bottom" },
              { label: "Esquerda", value: "left" },
              { label: "Direita", value: "right" },
            ],
          },
        ],
      },
      ...appearanceFields,
      ...gridAppearanceFields,
    ],
    previewConfig: { layout: "contained" },
    permissions: ["admin", "editor"],
    revisionStrategy: "snapshot",
  },
  TrustLogos: {
    type: "TrustLogos",
    label: "Logotipos de Fornecedores",
    description: "Vitrine de marcas oficiais representadas pela RECOM.",
    category: "content",
    component: TrustLogosBlock,
    schema: trustLogosSchema,
    defaults: {
      title: "Nossos Parceiros Oficiais",
      showAll: true,
      grayscale: true,
    },
    fields: [
      { name: "title", label: "Título Superior", type: "text" },
      { name: "showAll", label: "Mostrar Todos", type: "checkbox", description: "Se desmarcado, use IDs para filtrar." },
      { name: "grayscale", label: "Efeito P&B (Grayscale)", type: "checkbox" },
    ],
    previewConfig: { layout: "contained" },
    permissions: ["admin", "editor"],
    revisionStrategy: "snapshot",
  },
} satisfies Record<string, EditableComponentDefinition>;

export type CmsComponentType = keyof typeof componentRegistry;

export function getComponentDefinition(componentType: string) {
  return componentRegistry[componentType as CmsComponentType] ?? null;
}
